version: '3'

services:
  server:
    image: jetbrains/teamcity-server:latest
    networks:
      - web
      - default
    volumes:
      - "/opt/teamcity/data:/data/teamcity_server/datadir"
      - "/opt/teamcity/logs:/opt/teamcity/logs"
    hostname: ${VIRTUAL_HOST}
    ports:
      - "8111"
    depends_on:
      - postgres
    env_file: .env
    labels:
      - "traefik.enable=true"
      - "traefik.backend=server"
      - "traefik.frontend.rule=Host:${VIRTUAL_HOST}"
      - "traefik.docker.network=web"
      - "traefik.port=8111"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  agent:
    build: ./agents/python-node-yarn
    env_file: .env
    depends_on:
      - redis
    #     if you need docker inside the agent
    #     (http://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.enable=false"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  postgres:
    build: ./postgres
    volumes:
      - "/opt/teamcity/pg_data:/var/lib/postgresql/data"
      - "/opt/teamcity/pg_backup:/backups"
    env_file: .env
    labels:
      - "traefik.enable=false"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  redis:
    image: redis:3.2
    labels:
      - "traefik.enable=false"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  traefik:
    image: traefik:1.7-alpine
    restart: on-failure
    command:
      - --logLevel=ERROR
      - --docker
      - --docker.watch=true
      - --docker.exposedByDefault=false
      - --docker.domain=${VIRTUAL_HOST}
      - --defaultEntryPoints=http,https
      - --entryPoints=Name:http Address::80 Redirect.EntryPoint:https
      - --entryPoints=Name:https Address::443 TLS
      - --acme=true
      - --acme.domains=${LETSENCRYPT_HOST}
      - --acme.email=${LETSENCRYPT_EMAIL}
      - --acme.storage=acme.json
      - --acme.OnHostRule=false
      - --acme.onDemand=false
      - --acme.entryPoint=https
      - --acme.httpChallenge
      - --acme.httpChallenge.entryPoint=http
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/acme.json:/acme.json
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

networks:
  web:
    external: true
